### ISSUE TITLE
Error message received when trying to query Groups

### ISSUE THREAD

**Issue by jamesloughney** [datasert/realfire#17]
Hi, 

I receive the following error message and stack trace when I try and query the Group object type with the following query in the query Editor:

select Id, Name, CreatedById, CreatedDate, DeveloperName, DoesIncludeBosses, DoesSendEmailToMembers, Email, LastModifiedById, LastModifiedDate, OwnerId, RelatedId, SystemModstamp, Type from Group limit 10

java.lang.NullPointerException
	at com.datasert.realforce.internal.connection.bf.a(SfdcRestConnection.java:212)
	at com.datasert.realforce.internal.connection.e.b(Connection.java:818)
	at com.datasert.realforce.internal.f.b.o.b(QueryUtils.java:2808)
	at com.datasert.realforce.internal.f.b.o.a(QueryUtils.java:106)
	at com.datasert.realforce.uiapi.editor.queryeditor.QueryEditor.executeSoql(QueryEditor.java:165)
	at com.datasert.realforce.uiapi.editor.queryeditor.QueryEditor.executeQuery(QueryEditor.java:157)
	at com.datasert.realforce.internal.f.b.k.widgetSelected(QueryEditorToolbarWidget.java:61)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4238)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3817)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at com.datasert.realforce.ui.Application.start(Application.java:51)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)

**Comment by brsanthu** [comment]
Will take a look at this and update you.

**Comment by brsanthu** [comment]
@jamesloughney  We have fixed the issue and will be included in upcoming version (3.4). If you would like, I can send a beta release to that version.

**Comment by jamesloughney** [comment]
That's ok, it is not essential to what I am doing. Just thought you would like to know. I will wait for the next release version. Thanks.

**Comment by brsanthu** [comment]
Thank you for reporting. These reports helps stabilize the product.

If you are curious, it was due to keyword conflict (group by) in the parsing module.

**Comment by brsanthu** [comment]
@jamesloughney Version 3.4.7 is released with this fix in place. Thank you.
