### ISSUE TITLE
Searching Field threw java.lang.NullPointerException

### ISSUE THREAD

**Issue by jamesloughney** [datasert/realfire#19]
In my DEV org I previewed the Quote data by clicking on the Preview Data tab. I then selected my test record right clicked and selected 'View Full Record' from the Contaxt Menu.

![image](https://user-images.githubusercontent.com/3610332/37481713-afbcda30-283f-11e8-870d-87baa2d6ce52.png)

In the record screen that was displayed I then tried to Search the Fields by entering text into the Search Fields textbox:

![image](https://user-images.githubusercontent.com/3610332/37481850-07267b96-2840-11e8-8911-5f31f3d87467.png)

and then received the following error message:

java.lang.NullPointerException
	at com.datasert.realfire.internal.view.b.h.b(SoqlDatagrid.java:1043)
	at com.datasert.realfire.internal.c.bo.a(TextSearch.java:31)
	at com.datasert.realfire.internal.o.y.a(Utils.java:909)
	at com.datasert.realfire.internal.o.i.a(Utils.java:3104)
	at com.datasert.realfire.internal.o.y.run(Utils.java:909)
	at com.datasert.realfire.internal.o.i.d(Utils.java:959)
	at com.datasert.realfire.internal.o.i.a(Utils.java:3104)
	at com.datasert.realfire.internal.o.i.c(Utils.java:959)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:37)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4213)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3820)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at com.datasert.realfire.ui.Application.start(Application.java:58)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)

**Comment by brsanthu** [comment]
Thank you for reporting. Will take a look and release a fix.

**Comment by brsanthu** [comment]
Issue has been fixed in V4.2 which is salted to be released before tomorrow morning.
