### ISSUE TITLE
Can't NOT?

### ISSUE THREAD

**Issue by arthur3057** [datasert/realfire#30]
I can get the result in Workbench just fine, but not in Realfire (I am using it in trial mode). Why is this?

Realfire giving me this error:
com.datasert.sfsql.utils.DslException: Error parsing [Select Id, OwnerId, CaseNumber, Subject, Status, Incap311__SR_Ext_Id__c
FROM Case
WHERE (CaseNumber LIKE '2%') AND (Incap311__SR_Ext_Id__c = '') AND (NOT(Status LIKE 'Closed%'))]. Error: no viable alternative at input 'NOT', no viable alternative at input '(', extraneous input ')' expecting EOF
	at com.datasert.sfsql.utils.SfSqlUtils.validateNoErrors(SfSqlUtils.java:434)
	at com.datasert.sfsql.utils.SfSqlUtils.parseToModel(SfSqlUtils.java:406)
	at com.datasert.sfsql.utils.SfSqlUtils.parse(SfSqlUtils.java:395)
	at com.datasert.realfire.internal.editor.queryeditor.m.a(ScriptExecutor.java:176)
	at com.datasert.realfire.internal.editor.queryeditor.m.a(ScriptExecutor.java:167)
	at com.datasert.realfire.internal.editor.queryeditor.m.a(ScriptExecutor.java:121)
	at com.datasert.realfire.internal.editor.queryeditor.m.a(ScriptExecutor.java:54)
	at com.datasert.realfire.ui.editor.queryeditor.QueryEditor.executeQuery(QueryEditor.java:192)
	at com.datasert.realfire.ui.editor.queryeditor.QueryEditor.executeQuery(QueryEditor.java:156)
	at com.datasert.realfire.internal.editor.queryeditor.h.a(QueryEditorToolbarWidget.java:46)
	at com.datasert.realfire.internal.common.widgets.at.a(RfeToolBar.java:366)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4175)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3988)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3587)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:660)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
	at com.datasert.realfire.ui.Application.start(Application.java:52)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)

**Comment by brsanthu** [comment]
Please try this query which works. Essentially you need to remove the parenthesis after `not`

```
Select Id, OwnerId, CaseNumber, Subject, Status, Incap311__SR_Ext_Id__c
FROM Case
WHERE (CaseNumber LIKE '2%') AND (Incap311__SR_Ext_Id__c = '') AND (NOT Status LIKE 'Closed%')
```
