### ISSUE TITLE
Oauth hook  not working in client

### ISSUE THREAD

**Issue by birgirthor** [datasert/realfire#35]
System :  win10 fully updated, default browser Chrome fully updated, Realfire Essentials 5.3.2

Unable to authenticate with oauth

Oauth process opens the default browser, authentication is performed, redirect to "https://www.datasert.com/products/realfire/oauth-confirmation/"

The Realfire client picks nothing up and is stuck in loading/pending mode

I have been successful with the user/pass login method on same client

**Comment by birgirthor** [comment]
com.datasert.common.core.exception.BusinessException: Could not complete OAuth authentication [No response received from OAuth provider]
	at com.datasert.realfire.internal.connection.ak.a(LoginHandler.java:182)
	at com.datasert.realfire.internal.connection.l.f(Connection.java:432)
	at com.datasert.realfire.internal.connection.l.b(Connection.java:367)
	at com.datasert.realfire.internal.connection.l.a(Connection.java:351)
	at com.datasert.realfire.internal.connection.l.a(Connection.java:338)
	at com.datasert.realfire.internal.connection.l.a(Connection.java:2027)
	at com.datasert.realfire.internal.connection.l.a(Connection.java:2152)
	at com.datasert.realfire.internal.ag.ab.run(Utils.java:2098)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by g4ronliu** [comment]
Same issue for version 5.3.2.

com.datasert.common.core.exception.BusinessException: Could not complete OAuth authentication [No response received from OAuth provider]
	at com.datasert.realfire.internal.connection.ak.a(LoginHandler.java:182)
	at com.datasert.realfire.internal.connection.x.run(ConnectionTestingJob.java:49)
	at com.datasert.realfire.internal.ag.s.a(Utils.java:1971)
	at com.datasert.realfire.internal.ag.s.a(Utils.java:2054)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
